Update Ubuntu.yml

diff --git a/.github/workflows/Ubuntu.yml b/.github/workflows/Ubuntu.yml
--- a/.github/workflows/Ubuntu.yml
+++ b/.github/workflows/Ubuntu.yml
@@ -12,11 +12,36 @@ jobs:
 
     - name: Install Zrok CLI
       run: |
-        curl -LO https://zrok.io/download/zrok-linux-amd64
-        chmod +x zrok-linux-amd64
-        sudo mv zrok-linux-amd64 /usr/local/bin/zrok
+        cd $(mktemp -d);
+
+        ZROK_VERSION=$(
+          curl -sSf https://api.github.com/repos/openziti/zrok/releases/latest \
+          | jq -r '.tag_name'
+        );
+
+        case $(uname -m) in
+          x86_64)         GOXARCH=amd64
+          ;;
+          aarch64|arm64)  GOXARCH=arm64
+          ;;
+          arm*)           GOXARCH=arm
+          ;;
+          *)              echo "ERROR: unknown arch '$(uname -m)'" >&2
+                          exit 1
+          ;;
+        esac;
+
+        curl -sSfL \
+          "https://github.com/openziti/zrok/releases/download/${ZROK_VERSION}/zrok_${ZROK_VERSION#v}_linux_${GOXARCH}.tar.gz" \
+          | tar -xz -f -;
+
+        sudo install -o root -g root ./zrok /usr/local/bin/;
+
+        zrok version;
 
     - name: Configure Zrok for tunnel
+      env:
+        ZROK_TOKEN: ${{ secrets.ZROK_AUTH_TOKEN }}
       run: |
         zrok enable r99U4padYPE8
 
